# WiFi Configuration for Samsung Galaxy A30
# Copyright (C) 2026 TIBI624

# Enable IMPS or not
gEnableImps=1

# Enable BMPS or not
gEnableBmps=1

# Enable suspend or not
gEnableSuspend=3

# Enable Auto Shutdown
gEnableAutoBmpsTimer=0

# Phy Mode (auto, b, g, n, etc)
gDot11Mode=0

# UAPSD service interval for VO,VI, BE, BK traffic
InfraUapsdVoSrvIntv=0
InfraUapsdViSrvIntv=0
InfraUapsdBeSrvIntv=0
InfraUapsdBkSrvIntv=0

# Flag to allow STA send AddTspec even when ACM is Off
gAddTSWhenACMIsOff=1

# Enable OBSS protection
gEnableApOBSSProt=1

# Maximum Tx power
gMaxTxPower=255

# Enable/Disable STBC
gEnableTXSTBC=1

# Enable/Disable RX STBC
gEnableRXSTBC=1

# Enable/Disable LDPC
gEnableTXLDPC=1

# Enable/Disable Green AP
gGreenAP=0

# Enable/Disable Power Save Offload
gEnablePowerSaveOffload=2

# Firmware log mode
gFwDebugLogLevel=0

# Country code
gCountryCodePriority=1